//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pd_api {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageInfo() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pd_api.MessageInfo", typeof(MessageInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnego słownika..
        /// </summary>
        public static string Dictionary_CouldNotFindAnyDictionary {
            get {
                return ResourceManager.GetString("Dictionary_CouldNotFindAnyDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono słownika..
        /// </summary>
        public static string Dictionary_CouldNotFindDictionary {
            get {
                return ResourceManager.GetString("Dictionary_CouldNotFindDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpis z konfiguracją już istnieje w bazie danych..
        /// </summary>
        public static string Email_ConfigurationRecordAlreadyExist {
            get {
                return ResourceManager.GetString("Email_ConfigurationRecordAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można znaleźć ustawień poczty..
        /// </summary>
        public static string Email_CouldNotFindConfiguration {
            get {
                return ResourceManager.GetString("Email_CouldNotFindConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono zasobu {0}..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono..
        /// </summary>
        public static string Error_NotFoundAny {
            get {
                return ResourceManager.GetString("Error_NotFoundAny", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostęp nie dozwolony..
        /// </summary>
        public static string Login_AccessDenied {
            get {
                return ResourceManager.GetString("Login_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono użytkownika..
        /// </summary>
        public static string Login_CouldNotFindUser {
            get {
                return ResourceManager.GetString("Login_CouldNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie potwierdzono adresu e-mail..
        /// </summary>
        public static string Login_EmailAddress_NotConfirmed {
            get {
                return ResourceManager.GetString("Login_EmailAddress_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd z dupy dla google..
        /// </summary>
        public static string Login_GoogleAccountDontExist {
            get {
                return ResourceManager.GetString("Login_GoogleAccountDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd z dupa dla microsoft..
        /// </summary>
        public static string Login_MicrosoftAccountDontExist {
            get {
                return ResourceManager.GetString("Login_MicrosoftAccountDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono użytkownika..
        /// </summary>
        public static string User_CouldNotFindUser {
            get {
                return ResourceManager.GetString("User_CouldNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie przekazano nazwy użytkownika..
        /// </summary>
        public static string User_DidntPassUserName {
            get {
                return ResourceManager.GetString("User_DidntPassUserName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie prawidłowe hasło..
        /// </summary>
        public static string User_WrongPassword {
            get {
                return ResourceManager.GetString("User_WrongPassword", resourceCulture);
            }
        }
    }
}
